import { and, eq, isNotNull, ne } from "drizzle-orm";

import { db } from "@/db/client";
import { workOrders } from "@/db/schema";
import type { CalendarEvent } from "@/lib/calendar/types";

const TERMINAL_STATUSES = new Set(["resolved", "closed", "cancelled"]);

export interface WorkOrderCalendarRow {
  id: string;
  organizationId: string;
  number: string;
  subject: string;
  propertyId: string;
  vendorId: string | null;
  assignedUserId: string | null;
  status: string;
  source: string;
  scheduledStartAt: Date | null;
  scheduledEndAt: Date | null;
}

/**
 * Projects a scheduled Work Order onto the calendar. Returns null for a Work
 * Order with no scheduled time (nothing to plot) or one generated by
 * Preventive Maintenance (that Work Order is instead represented by the PM
 * projection — see lib/calendar/projections/preventive-maintenance.ts — so
 * it is never shown twice).
 */
export function projectWorkOrderEvent(
  row: WorkOrderCalendarRow,
  now: Date,
): CalendarEvent | null {
  if (!row.scheduledStartAt || row.source === "preventive_maintenance") {
    return null;
  }

  const overdue = row.scheduledStartAt < now && !TERMINAL_STATUSES.has(row.status);

  return {
    id: `work_order:${row.id}`,
    organizationId: row.organizationId,
    sourceType: "work_order",
    sourceId: row.id,
    category: "work_order_scheduled",
    title: `${row.number}: ${row.subject}`,
    startAt: row.scheduledStartAt.toISOString(),
    endAt: row.scheduledEndAt ? row.scheduledEndAt.toISOString() : null,
    allDay: false,
    propertyId: row.propertyId,
    vendorId: row.vendorId,
    assignedUserId: row.assignedUserId,
    status: row.status,
    statusLabel: row.status,
    overdue,
    deepLinkUrl: `/work-orders/${row.id}`,
    metadata: {},
  };
}

export async function fetchWorkOrderEvents(
  organizationId: string,
  now: Date,
): Promise<CalendarEvent[]> {
  const rows = await db
    .select({
      id: workOrders.id,
      organizationId: workOrders.organizationId,
      number: workOrders.number,
      subject: workOrders.subject,
      propertyId: workOrders.propertyId,
      vendorId: workOrders.vendorId,
      assignedUserId: workOrders.assignedUserId,
      status: workOrders.status,
      source: workOrders.source,
      scheduledStartAt: workOrders.scheduledStartAt,
      scheduledEndAt: workOrders.scheduledEndAt,
    })
    .from(workOrders)
    .where(
      and(
        eq(workOrders.organizationId, organizationId),
        isNotNull(workOrders.scheduledStartAt),
        ne(workOrders.source, "preventive_maintenance"),
      ),
    );

  return rows
    .map((row) => projectWorkOrderEvent(row, now))
    .filter((event): event is CalendarEvent => event !== null);
}
